SET TERMOUT ONPROMPT Building demonstration tables.  
Please wait.PROMPT Dropping pre-existing tables. 
If this errors, remove the drop scripts.

DROP TABLE CARMAINTENANCE CASCADE CONSTRAINTS;
DROP TABLE EXPENSES CASCADE CONSTRAINTS;
DROP TABLE REVENUE CASCADE CONSTRAINTS;
DROP TABLE PAIDSALARIES CASCADE CONSTRAINTS;
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE SHARES CASCADE CONSTRAINTS;
DROP TABLE BOOKINGS CASCADE CONSTRAINTS;
DROP TABLE CLIENTS CASCADE CONSTRAINTS;
DROP TABLE SHIFTS CASCADE CONSTRAINTS;
DROP TABLE SHIFTDAYS CASCADE CONSTRAINTS;
DROP TABLE OPERATORS CASCADE CONSTRAINTS;
DROP TABLE DRIVERS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE RATES CASCADE CONSTRAINTS;
DROP TABLE CARS CASCADE CONSTRAINTS;
DROP TABLE CARSTATUS CASCADE CONSTRAINTS;

DROP SEQUENCE RateID_Seq;
DROP SEQUENCE CarStatusID_Seq;
DROP SEQUENCE ExpenseID_Seq;
DROP SEQUENCE ClientID_Seq;
DROP SEQUENCE ShiftID_Seq;
DROP SEQUENCE ShiftDaysID_Seq;
DROP SEQUENCE PaymentID_Seq;
DROP SEQUENCE ShareID_Seq;
DROP SEQUENCE OperatorID_Seq;
DROP SEQUENCE DriverID_Seq;
DROP SEQUENCE EmployeeID_Seq;
DROP SEQUENCE BookingID_Seq;

PROMPT Creating Sequences.

CREATE SEQUENCE CarStatusID_Seq
MINVALUE 0 
START WITH 0 
INCREMENT BY 1;

CREATE SEQUENCE ExpenseID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE ClientID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE ShiftDaysID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE ShiftID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE PaymentID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE ShareID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE OperatorID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE DriverID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE EmployeeID_Seq
MINVALUE 0
START WITH 0
INCREMENT BY 1;

CREATE SEQUENCE BookingID_Seq
MINVALUE 0
START WITH 1
INCREMENT BY 1;

PROMPT Building CarStatus relation.

CREATE TABLE CarStatus(	
StatusID NUMBER(6) NOT NULL,
Description VARCHAR(20) NOT NULL,
CONSTRAINT CarStatus_PK PRIMARY KEY(StatusID),
CONSTRAINT CarStatus_Check CHECK (Description IN ('Roadworthy', 'In for Service', 'Awaiting Repair', 'Written Off')));

CREATE TABLE Cars(	
RegNo VARCHAR(7) NOT NULL,
MakeYear DATE NOT NULL,	MOTDate DATE NOT NULL,
TaxDate DATE NOT NULL,	StatusID NUMBER(6) NOT NULL,
Owner VARCHAR(13) NOT NULL,CONSTRAINT Cars_RegNo_PK PRIMARY KEY(RegNo),
CONSTRAINT Cars_Status_FK FOREIGN KEY(StatusID) REFERENCES CarStatus(StatusID),
CONSTRAINT Cars_Owner_Check CHECK (Owner IN ('Company','Driver')));

CREATE TABLE ShiftDays(	
ShiftDaysID NUMBER(6) NOT NULL,
Monday VARCHAR(1) NOT NULL,
Tuesday VARCHAR(1) NOT NULL,
Wednesday VARCHAR(1) NOT NULL,
Thursday VARCHAR(1) NOT NULL,
Friday VARCHAR(1) NOT NULL,
Saturday VARCHAR(1) NOT NULL,
Sunday VARCHAR(1) NOT NULL,CONSTRAINT ShiftDays_PK PRIMARY KEY(ShiftDaysID),
CONSTRAINT ShiftDays_Monday_Check CHECK(Monday IN ('Y','N')),
CONSTRAINT ShiftDays_Tuesday_Check CHECK(Tuesday IN ('Y','N')),
CONSTRAINT ShiftDays_Wednesday_Check CHECK(Wednesday IN ('Y','N')),
CONSTRAINT ShiftDays_Thursday_Check CHECK(Thursday IN ('Y','N')),
CONSTRAINT ShiftDays_Friday_Check CHECK(Friday IN ('Y','N')),
CONSTRAINT ShiftDays_Saturday_Check CHECK(Saturday IN ('Y','N')),
CONSTRAINT ShiftDays_Sunday_Check CHECK(Sunday IN ('Y','N')));

CREATE TABLE Shifts(
ShiftID NUMBER(6) NOT NULL,
StartHours NUMBER(2) NOT NULL,
EndHours NUMBER(2) NOT NULL,
ShiftDaysID NUMBER(6) NOT NULL,
CONSTRAINT Shifts_PK PRIMARY KEY (ShiftID),
CONSTRAINT Shifts_ShiftDaysID FOREIGN KEY (ShiftDaysID) REFERENCES ShiftDays(ShiftDaysID));

CREATE TABLE Employees(
EmployeeID NUMBER(6) NOT NULL,
EmployeeInfo XMLTYPE NOT NULL,
CONSTRAINT Employees_EmployeeID_PK PRIMARY KEY (EmployeeID));

CREATE TABLE Drivers(
DriverID NUMBER(6) NOT NULL,
EmployeeID NUMBER(6) UNIQUE NOT NULL,
CabPhoneNo NUMBER(11) NOT NULL,
CabRegNo VARCHAR(7) NOT NULL,
CONSTRAINT Drivers_DriverID_PK PRIMARY KEY (DriverID),
CONSTRAINT Drivers_EmployeeID_FK FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
CONSTRAINT Drivers_CabRegNo_FK FOREIGN KEY (CabRegNo) REFERENCES Cars(RegNo));

CREATE TABLE Operators(
OperatorID NUMBER(6) NOT NULL,
EmployeeID NUMBER(6) UNIQUE NOT NULL,
CONSTRAINT Operators_OperatorID_PK PRIMARY KEY (OperatorID),
CONSTRAINT Operators_EmployeeID_FK FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) );

CREATE TABLE Clients(
ClientID NUMBER(6) NOT NULL,
ClientInfo XMLTYPE NOT NULL,
CONSTRAINT Clients_ClientID_PK PRIMARY KEY (ClientID));

CREATE TABLE Bookings(
BookingID NUMBER(6) NOT NULL,
BookingInfo XMLTYPE NOT NULL,
CONSTRAINT Bookings_PK PRIMARY KEY(BookingID));

CREATE TABLE Payments(
PaymentID NUMBER(6) NOT NULL,
BookingID NUMBER(6) NOT NULL,
DriverID NUMBER(6) NOT NULL,
PaymentDate DATE NOT NULL,
Ammount NUMBER(7,2) NOT NULL,
PaymentType VARCHAR(4) NOT NULL,
OriginalPickUpDate DATE NOT NULL,
CONSTRAINT Payments_PK PRIMARY KEY (PaymentID),
CONSTRAINT Payments_DriverID_FK FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID),
CONSTRAINT Payments_BookingID_FK FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID),
CONSTRAINT Payments_PaymentType_Check CHECK (PaymentType IN ('Card', 'Cash')));

CREATE TABLE PaidSalaries(
EmployeeID NUMBER(6) NOT NULL,
DatePaid DATE NOT NULL,	
FromDate DATE NOT NULL,	ToDate DATE NOT NULL,
HoursWorked NUMBER(4) NOT NULL,	
Salary NUMBER(7,2) NOT NULL,
AtRate NUMBER(4) NOT NULL,
CONSTRAINT PaidSalaries_EmployeeID_FK FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
CONSTRAINT PaidSalaries_HoursWorked CHECK (HoursWorked > 0));

CREATE TABLE Shares(
ShareID NUMBER(6) NOT NULL,	
PaymentID NUMBER(6) NOT NULL,
DriverShare NUMBER(6) NOT NULL,
CompanyShare NUMBER(6) NOT NULL,CONSTRAINT Shares_ShareID_PK PRIMARY KEY (ShareID),
CONSTRAINT Shares_PaymentID_FK FOREIGN KEY (PaymentID) REFERENCES Payments(PaymentID));

CREATE TABLE Revenue(
DateFrom DATE NOT NULL,
DateTo DATE NOT NULL,
TotalCosts NUMBER(7,2) NOT NULL,
TotalIncome NUMBER(7,2) NOT NULL,
Profit NUMBER(7,2) NOT NULL,
DateCalculated DATE NOT NULL,
CONSTRAINT Revenue_PK PRIMARY KEY(DateFrom,DateTo));

CREATE TABLE Expenses(
ExpenseID NUMBER(6) NOT NULL,
ExpenseInfo XMLTYPE NOT NULL,CONSTRAINT Expenses_PK PRIMARY KEY(ExpenseID));

COMMIT;
